/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    active: boolean;
    dateOfBirth: string;
    name: string;
    contactEmail: string;
    enrollmentDate: string;
    teamId?: bigint;
    position: Position;
    parentName: string;
    contactPhone: string;
}
export interface Coach {
    id: bigint;
    active: boolean;
    name: string;
    email: string;
    specialization: Specialization;
    phone: string;
}
export interface TrainingSession {
    id: bigint;
    date: string;
    time: string;
    notes: string;
    teamId: bigint;
    location: string;
}
export interface SummaryStats {
    totalTeams: bigint;
    totalPlayers: bigint;
    totalCoaches: bigint;
    upcomingSessions: bigint;
}
export interface Match {
    id: bigint;
    venue: string;
    goalsFor: bigint;
    notes: string;
    homeOrAway: HomeOrAway;
    goalsAgainst: bigint;
    teamId: bigint;
    opponent: string;
    matchDate: string;
}
export interface UserProfile {
    name: string;
}
export interface Team {
    id: bigint;
    active: boolean;
    name: string;
    coachId: bigint;
    ageGroup: AgeGroup;
}
export enum AgeGroup {
    U8 = "U8",
    U10 = "U10",
    U12 = "U12",
    U14 = "U14",
    U16 = "U16",
    U18 = "U18",
    senior = "senior"
}
export enum HomeOrAway {
    away = "away",
    home = "home"
}
export enum Position {
    goalkeeper = "goalkeeper",
    midfielder = "midfielder",
    forward = "forward",
    defender = "defender"
}
export enum Specialization {
    midfield = "midfield",
    goalkeeping = "goalkeeping",
    defense = "defense",
    fitness = "fitness",
    attacking = "attacking"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCoach(coach: Coach): Promise<bigint>;
    createMatch(match: Match): Promise<bigint>;
    createPlayer(player: Player): Promise<bigint>;
    createTeam(team: Team): Promise<bigint>;
    createTrainingSession(session: TrainingSession): Promise<bigint>;
    deleteCoach(id: bigint): Promise<void>;
    deleteMatch(id: bigint): Promise<void>;
    deletePlayer(id: bigint): Promise<void>;
    deleteTeam(id: bigint): Promise<void>;
    deleteTrainingSession(id: bigint): Promise<void>;
    getAllCoaches(): Promise<Array<Coach>>;
    getAllMatches(): Promise<Array<Match>>;
    getAllPlayers(): Promise<Array<Player>>;
    getAllTeams(): Promise<Array<Team>>;
    getAllTrainingSessions(): Promise<Array<TrainingSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoachById(id: bigint): Promise<Coach>;
    getMatchById(id: bigint): Promise<Match>;
    getPlayerById(id: bigint): Promise<Player>;
    getSummaryStats(): Promise<SummaryStats>;
    getTeamById(id: bigint): Promise<Team>;
    getTrainingSessionById(id: bigint): Promise<TrainingSession>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCoach(id: bigint, coach: Coach): Promise<void>;
    updateMatch(id: bigint, match: Match): Promise<void>;
    updatePlayer(id: bigint, player: Player): Promise<void>;
    updateTeam(id: bigint, team: Team): Promise<void>;
    updateTrainingSession(id: bigint, session: TrainingSession): Promise<void>;
}
import type { AgeGroup as _AgeGroup, Coach as _Coach, HomeOrAway as _HomeOrAway, Match as _Match, Player as _Player, Position as _Position, Specialization as _Specialization, Team as _Team, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCoach(arg0: Coach): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoach(to_candid_Coach_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoach(to_candid_Coach_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMatch(arg0: Match): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(to_candid_Match_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(to_candid_Match_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPlayer(arg0: Player): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(to_candid_Player_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(to_candid_Player_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTeam(arg0: Team): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(to_candid_Team_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(to_candid_Team_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTrainingSession(arg0: TrainingSession): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrainingSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrainingSession(arg0);
            return result;
        }
    }
    async deleteCoach(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoach(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoach(arg0);
            return result;
        }
    }
    async deleteMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async deletePlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async deleteTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeam(arg0);
            return result;
        }
    }
    async deleteTrainingSession(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrainingSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrainingSession(arg0);
            return result;
        }
    }
    async getAllCoaches(): Promise<Array<Coach>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoaches();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoaches();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrainingSessions(): Promise<Array<TrainingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrainingSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrainingSessions();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoachById(arg0: bigint): Promise<Coach> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachById(arg0);
                return from_candid_Coach_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachById(arg0);
            return from_candid_Coach_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchById(arg0: bigint): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchById(arg0);
                return from_candid_Match_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchById(arg0);
            return from_candid_Match_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerById(arg0: bigint): Promise<Player> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerById(arg0);
                return from_candid_Player_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerById(arg0);
            return from_candid_Player_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummaryStats(): Promise<SummaryStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryStats();
            return result;
        }
    }
    async getTeamById(arg0: bigint): Promise<Team> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamById(arg0);
                return from_candid_Team_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamById(arg0);
            return from_candid_Team_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrainingSessionById(arg0: bigint): Promise<TrainingSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainingSessionById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainingSessionById(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCoach(arg0: bigint, arg1: Coach): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoach(arg0, to_candid_Coach_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoach(arg0, to_candid_Coach_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMatch(arg0: bigint, arg1: Match): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatch(arg0, to_candid_Match_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatch(arg0, to_candid_Match_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlayer(arg0: bigint, arg1: Player): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, to_candid_Player_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, to_candid_Player_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTeam(arg0: bigint, arg1: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(arg0, to_candid_Team_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(arg0, to_candid_Team_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTrainingSession(arg0: bigint, arg1: TrainingSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainingSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainingSession(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AgeGroup_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgeGroup): AgeGroup {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Coach_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coach): Coach {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_HomeOrAway_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomeOrAway): HomeOrAway {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Player_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Player): Player {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Specialization_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Specialization): Specialization {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    name: string;
    email: string;
    specialization: _Specialization;
    phone: string;
}): {
    id: bigint;
    active: boolean;
    name: string;
    email: string;
    specialization: Specialization;
    phone: string;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        email: value.email,
        specialization: from_candid_Specialization_n22(_uploadFile, _downloadFile, value.specialization),
        phone: value.phone
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    venue: string;
    goalsFor: bigint;
    notes: string;
    homeOrAway: _HomeOrAway;
    goalsAgainst: bigint;
    teamId: bigint;
    opponent: string;
    matchDate: string;
}): {
    id: bigint;
    venue: string;
    goalsFor: bigint;
    notes: string;
    homeOrAway: HomeOrAway;
    goalsAgainst: bigint;
    teamId: bigint;
    opponent: string;
    matchDate: string;
} {
    return {
        id: value.id,
        venue: value.venue,
        goalsFor: value.goalsFor,
        notes: value.notes,
        homeOrAway: from_candid_HomeOrAway_n27(_uploadFile, _downloadFile, value.homeOrAway),
        goalsAgainst: value.goalsAgainst,
        teamId: value.teamId,
        opponent: value.opponent,
        matchDate: value.matchDate
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    dateOfBirth: string;
    name: string;
    contactEmail: string;
    enrollmentDate: string;
    teamId: [] | [bigint];
    position: _Position;
    parentName: string;
    contactPhone: string;
}): {
    id: bigint;
    active: boolean;
    dateOfBirth: string;
    name: string;
    contactEmail: string;
    enrollmentDate: string;
    teamId?: bigint;
    position: Position;
    parentName: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        active: value.active,
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        contactEmail: value.contactEmail,
        enrollmentDate: value.enrollmentDate,
        teamId: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.teamId)),
        position: from_candid_Position_n33(_uploadFile, _downloadFile, value.position),
        parentName: value.parentName,
        contactPhone: value.contactPhone
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    name: string;
    coachId: bigint;
    ageGroup: _AgeGroup;
}): {
    id: bigint;
    active: boolean;
    name: string;
    coachId: bigint;
    ageGroup: AgeGroup;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        coachId: value.coachId,
        ageGroup: from_candid_AgeGroup_n38(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    midfield: null;
} | {
    goalkeeping: null;
} | {
    defense: null;
} | {
    fitness: null;
} | {
    attacking: null;
}): Specialization {
    return "midfield" in value ? Specialization.midfield : "goalkeeping" in value ? Specialization.goalkeeping : "defense" in value ? Specialization.defense : "fitness" in value ? Specialization.fitness : "attacking" in value ? Specialization.attacking : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    away: null;
} | {
    home: null;
}): HomeOrAway {
    return "away" in value ? HomeOrAway.away : "home" in value ? HomeOrAway.home : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalkeeper: null;
} | {
    midfielder: null;
} | {
    forward: null;
} | {
    defender: null;
}): Position {
    return "goalkeeper" in value ? Position.goalkeeper : "midfielder" in value ? Position.midfielder : "forward" in value ? Position.forward : "defender" in value ? Position.defender : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    U8: null;
} | {
    U10: null;
} | {
    U12: null;
} | {
    U14: null;
} | {
    U16: null;
} | {
    U18: null;
} | {
    senior: null;
}): AgeGroup {
    return "U8" in value ? AgeGroup.U8 : "U10" in value ? AgeGroup.U10 : "U12" in value ? AgeGroup.U12 : "U14" in value ? AgeGroup.U14 : "U16" in value ? AgeGroup.U16 : "U18" in value ? AgeGroup.U18 : "senior" in value ? AgeGroup.senior : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coach>): Array<Coach> {
    return value.map((x)=>from_candid_Coach_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Player>): Array<Player> {
    return value.map((x)=>from_candid_Player_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n36(_uploadFile, _downloadFile, x));
}
function to_candid_AgeGroup_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): _AgeGroup {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Coach_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Coach): _Coach {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_HomeOrAway_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomeOrAway): _HomeOrAway {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Match_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Match): _Match {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Player_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Player): _Player {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_Position_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Specialization_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Specialization): _Specialization {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Team_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Team): _Team {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    dateOfBirth: string;
    name: string;
    contactEmail: string;
    enrollmentDate: string;
    teamId?: bigint;
    position: Position;
    parentName: string;
    contactPhone: string;
}): {
    id: bigint;
    active: boolean;
    dateOfBirth: string;
    name: string;
    contactEmail: string;
    enrollmentDate: string;
    teamId: [] | [bigint];
    position: _Position;
    parentName: string;
    contactPhone: string;
} {
    return {
        id: value.id,
        active: value.active,
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        contactEmail: value.contactEmail,
        enrollmentDate: value.enrollmentDate,
        teamId: value.teamId ? candid_some(value.teamId) : candid_none(),
        position: to_candid_Position_n13(_uploadFile, _downloadFile, value.position),
        parentName: value.parentName,
        contactPhone: value.contactPhone
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    name: string;
    coachId: bigint;
    ageGroup: AgeGroup;
}): {
    id: bigint;
    active: boolean;
    name: string;
    coachId: bigint;
    ageGroup: _AgeGroup;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        coachId: value.coachId,
        ageGroup: to_candid_AgeGroup_n17(_uploadFile, _downloadFile, value.ageGroup)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    name: string;
    email: string;
    specialization: Specialization;
    phone: string;
}): {
    id: bigint;
    active: boolean;
    name: string;
    email: string;
    specialization: _Specialization;
    phone: string;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        email: value.email,
        specialization: to_candid_Specialization_n5(_uploadFile, _downloadFile, value.specialization),
        phone: value.phone
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    venue: string;
    goalsFor: bigint;
    notes: string;
    homeOrAway: HomeOrAway;
    goalsAgainst: bigint;
    teamId: bigint;
    opponent: string;
    matchDate: string;
}): {
    id: bigint;
    venue: string;
    goalsFor: bigint;
    notes: string;
    homeOrAway: _HomeOrAway;
    goalsAgainst: bigint;
    teamId: bigint;
    opponent: string;
    matchDate: string;
} {
    return {
        id: value.id,
        venue: value.venue,
        goalsFor: value.goalsFor,
        notes: value.notes,
        homeOrAway: to_candid_HomeOrAway_n9(_uploadFile, _downloadFile, value.homeOrAway),
        goalsAgainst: value.goalsAgainst,
        teamId: value.teamId,
        opponent: value.opponent,
        matchDate: value.matchDate
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomeOrAway): {
    away: null;
} | {
    home: null;
} {
    return value == HomeOrAway.away ? {
        away: null
    } : value == HomeOrAway.home ? {
        home: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): {
    goalkeeper: null;
} | {
    midfielder: null;
} | {
    forward: null;
} | {
    defender: null;
} {
    return value == Position.goalkeeper ? {
        goalkeeper: null
    } : value == Position.midfielder ? {
        midfielder: null
    } : value == Position.forward ? {
        forward: null
    } : value == Position.defender ? {
        defender: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AgeGroup): {
    U8: null;
} | {
    U10: null;
} | {
    U12: null;
} | {
    U14: null;
} | {
    U16: null;
} | {
    U18: null;
} | {
    senior: null;
} {
    return value == AgeGroup.U8 ? {
        U8: null
    } : value == AgeGroup.U10 ? {
        U10: null
    } : value == AgeGroup.U12 ? {
        U12: null
    } : value == AgeGroup.U14 ? {
        U14: null
    } : value == AgeGroup.U16 ? {
        U16: null
    } : value == AgeGroup.U18 ? {
        U18: null
    } : value == AgeGroup.senior ? {
        senior: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Specialization): {
    midfield: null;
} | {
    goalkeeping: null;
} | {
    defense: null;
} | {
    fitness: null;
} | {
    attacking: null;
} {
    return value == Specialization.midfield ? {
        midfield: null
    } : value == Specialization.goalkeeping ? {
        goalkeeping: null
    } : value == Specialization.defense ? {
        defense: null
    } : value == Specialization.fitness ? {
        fitness: null
    } : value == Specialization.attacking ? {
        attacking: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
